modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/ZoeTheDaw/HalcyonHorizons/issues" #optional
[[mods]] #mandatory
modId="halcyonhorizons" #mandatory
version="1.0.0" #mandatory
displayName="Halcyon Horizons" #mandatory
displayURL="" #optional
authors="ZoeTheDaw, Trafficone, Tissuebounce" #optional
credits="" #optional
description='''Testy WEsty'''
logoFile="" #optional
[[dependencies.halcyonhorizons]] #optional
# the modid of the dependency
modId="citadel" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[2.6.0,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="AFTER"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
[[dependencies.halcyonhorizons]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"